services:
  postgres:
    container_name: postgres
    image: ghcr.io/polarix-containers/postgres:17
    restart: unless-stopped
    volumes:
      - ./postgres:/var/lib/postgresql/data:Z
    networks:
      - postgres
    env_file:
      - postgres.env
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "authentik"]
      interval: 15s
      timeout: 5s
    user: "200012:200012"
    read_only: true
    tmpfs:
      - /var/run/postgresql:size=50M,mode=0770,uid=200012,gid=200012,noexec,nosuid,nodev
    security_opt:
      - "no-new-privileges=true"
    cap_drop:
      - ALL

  valkey:
    container_name: valkey
    image: ghcr.io/polarix-containers/valkey:8
    restart: unless-stopped
    volumes:
      - ./valkey:/data:Z
    networks:
      - valkey
    healthcheck:
      test: ["CMD-SHELL", "valkey-cli ping | grep PONG"]
      interval: 15s
      timeout: 5s
    user: "200010:200010"
    read_only: true
    security_opt:
      - "no-new-privileges=true"
    cap_drop:
      - ALL

  server:
    container_name: server
    image: ghcr.io/goauthentik/server:2025.6.4
    restart: unless-stopped
    command: server
    volumes:
      - ./authentik/media:/media:z
      - ./authentik/custom-templates:/templates:z
    ports:
      - "9000:9000"
      - "9443:9443"
    networks:
      - postgres
      - valkey
    depends_on:
      postgres:
        condition: service_healthy
      valkey:
        condition: service_healthy
    env_file:
      - authentik.env
    user: "200001:200001"
    read_only: true
    security_opt:
      - "no-new-privileges=true"
    cap_drop:
      - ALL

  worker:
    container_name: worker
    image: ghcr.io/goauthentik/server:2025.6.4
    restart: unless-stopped
    command: worker
    volumes:
      - ./authentik/media:/media:z
      - ./authentik/certs:/certs:Z
      - ./authentik/custom-templates:/templates:z
    networks:
      - postgres
      - valkey
    depends_on:
      postgres:
        condition: service_healthy
      valkey:
        condition: service_healthy
    env_file:
      - authentik.env
    user: "200001:200001"
    read_only: true
    security_opt:
      - "no-new-privileges=true"
    cap_drop:
      - ALL

networks:
  postgres:
  valkey:
