services:
  mariadb:
    container_name: mariadb
    restart: unless-stopped
    image: ghcr.io/polarix-containers/mariadb:11.4-alpine
    volumes:
      - "./mariadb:/var/lib/mysql:Z"
    networks:
      - mariadb
    env_file:
      - mariadb.env
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 15s
      timeout: 5s
    user: "200011:200011"
    read_only: true
    tmpfs:
      - /var/tmp:mode=0770,uid=200011,gid=200011,noexec,nosuid,nodev
      - /run/mariadb:size=50M,mode=0770,uid=200011,gid=200011,noexec,nosuid,nodev
    security_opt:
      - "no-new-privileges=true"
    cap_drop:
      - ALL

  valkey:
    container_name: valkey
    image: ghcr.io/polarix-containers/valkey:8
    restart: unless-stopped
    volumes:
      - ./valkey:/data:Z
    networks:
      - valkey
    healthcheck:
      test: ["CMD-SHELL", "valkey-cli ping | grep PONG"]
      interval: 15s
      timeout: 5s
    user: "200010:200010"
    read_only: true
    security_opt:
      - "no-new-privileges=true"
    cap_drop:
      - ALL

  nextcloud:
    container_name: nextcloud
    image: ghcr.io/polarix-containers/nextcloud:latest
    restart: unless-stopped
    volumes:
      - ./nextcloud:/var/www/html:z
    networks:
      - mariadb
      - valkey
      - nginx
    depends_on:
      mariadb:
        condition: service_healthy
      valkey:
        condition: service_healthy
    env_file:
      - nextcloud.env
    security_opt:
      - "no-new-privileges=true"
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - SETUID
      - SETGID

  cron:
    container_name: cron
    image: ghcr.io/polarix-containers/nextcloud:latest
    restart: unless-stopped
    volumes:
      - ./nextcloud:/var/www/html:z
    networks:
      - mariadb
      - valkey
    depends_on:
      mariadb:
        condition: service_healthy
      valkey:
        condition: service_healthy
    entrypoint: /cron.sh
    security_opt:
      - "no-new-privileges=true"
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID

  nginx:
    container_name: nginx
    restart: unless-stopped
    image: ghcr.io/polarix-containers/nginx:unprivileged-slim
    ports:
      - 8443:8443/tcp
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:Z,ro
      - ./nextcloud:/var/www/html:z
      - ./certs:/certs:z,ro
    networks:
      - nginx
    depends_on:
      nextcloud:
        condition: service_started
    user: "101:101"
    read_only: true
    tmpfs:
      - /var/cache/nginx:mode=0770,uid=101,gid=101,noexec,nosuid,nodev
      - /tmp:mode=0770,uid=101,gid=101,noexec,nosuid,nodev
    security_opt:
      - "no-new-privileges=true"
    cap_drop:
      - ALL

networks:
  mariadb:
  valkey:
  nginx: